package com.protect.love.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.protect.love.bean.OpenProtectUser;

import com.protect.love.dao.OpenProtectUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig openProtectUserDaoConfig;

    private final OpenProtectUserDao openProtectUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        openProtectUserDaoConfig = daoConfigMap.get(OpenProtectUserDao.class).clone();
        openProtectUserDaoConfig.initIdentityScope(type);

        openProtectUserDao = new OpenProtectUserDao(openProtectUserDaoConfig, this);

        registerDao(OpenProtectUser.class, openProtectUserDao);
    }
    
    public void clear() {
        openProtectUserDaoConfig.clearIdentityScope();
    }

    public OpenProtectUserDao getOpenProtectUserDao() {
        return openProtectUserDao;
    }

}
